name: Auto Assign Issue to Creator

on:
  issues:
    types: [opened]

permissions:
    issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - name: Assign the issue to the creator
      run: |
        curl \
          -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d '{"assignees": ["${{ github.actor }}"]}'
